<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Articles_model extends CI_Model
{

    public $table = 'articles';
    public $id = 'idartikel';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('idartikel,
            kategori.idkategori,kategori.nama_kategori,tags,title,
            slug,body,image,articles.status,
            articles.create_date,
            articles.modif_date');
        $this->datatables->from('articles');
        //add this line for join
        $this->datatables->join('kategori', 'kategori.idkategori = articles.idkategori');
        $this->datatables->add_column('action', 
            
            '
           
            
           

                  
                                                   <a href="javascript:void(0);" class="view_artikel label label-sm label-info" data-view="$1" ><i class="fa fa-eye"></i> View</a>  
                                                
                                                   <a href="javascript:void(0);" class="edit_artikel label label-sm label-info" data-code="$1" ><i class="fa fa-pencil"></i> Edit</a> 
                                                
                                                   <a href="javascript:void(0);" class="delete_artikel label label-sm label-danger" data-code="$1" data-judul="$2"><i class="fa fa-trash-o"></i> Hapus</a> 
                                               
                                      



            ','idartikel,title');
        return $this->datatables->generate();
    
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

 

    // get data by id
    function get_by_id($slug)
    {
        $this->db->where('slug', $slug);
        return $this->db->get($this->table)->row();
    }

      function Editget_by_id($idartikel)
    {
        $this->db->where('idartikel', $idartikel);
        return $this->db->get($this->table)->row();
    }

    
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idartikel', $q);
	$this->db->or_like('idkategori', $q);
	$this->db->or_like('idtag', $q);
	$this->db->or_like('title', $q);
	$this->db->or_like('slug', $q);
	$this->db->or_like('body', $q);
	$this->db->or_like('image', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('create_date', $q);
	$this->db->or_like('modif_date', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idartikel', $q);
	$this->db->or_like('idkategori', $q);
	$this->db->or_like('idtag', $q);
	$this->db->or_like('title', $q);
	$this->db->or_like('slug', $q);
	$this->db->or_like('body', $q);
	$this->db->or_like('image', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('create_date', $q);
	$this->db->or_like('modif_date', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
      $cek =   $this->db->update($this->table, $data);
        if($cek){

            return true;
        }else{
            return false;
        }

    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Articles_model.php */
/* Location: ./application/models/Articles_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-05-11 11:09:53 */
/* http://harviacode.com */