<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Faq_model extends CI_Model
{

    public $table = 'faq';
    public $id = 'idfaq';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('idfaq,judul,keterangan,createdate,modifdate');
        $this->datatables->from('faq');
        //add this line for join
        //$this->datatables->join('table2', 'faq.field = table2.field');
        // $this->datatables->add_column('action', anchor(site_url('faq/read/$1'),'<i class="fa fa-eye-open"></i>')." | ".anchor(site_url('faq/update/$1'),'Edit')." | ".anchor(site_url('faq/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'idfaq');

        $this->datatables->add_column('action', '
 		<a href="javascript:void(0);" class="edit_record  label label-sm label-info" data-code="$1" ><i class="fa fa-pencil"></i> Edit</a>
         <a href="javascript:void(0);" class="delete_record label label-sm label-danger" data-code="$1" data-judul="$2"><i class="fa fa-trash-o"></i> Hapus</a>
           ',  'idfaq,judul');

        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('idfaq', $q);
        $this->db->or_like('judul', $q);
        $this->db->or_like('keterangan', $q);
        $this->db->or_like('createdate', $q);
        $this->db->or_like('modifdate', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idfaq', $q);
        $this->db->or_like('judul', $q);
        $this->db->or_like('keterangan', $q);
        $this->db->or_like('createdate', $q);
        $this->db->or_like('modifdate', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Faq_model.php */
/* Location: ./application/models/Faq_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-10-14 13:45:40 */
/* http://harviacode.com */
