<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Galeri_model extends CI_Model
{

    public $table   = 'galeri';
    public $id      = 'idgalery';
    public $order   = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

 
    // datatables
    function json() {
        $this->datatables->select('idgalery,galeri.idkategori,count(galeri.idkategori) as                              total,kategori.nama_kategori');
        $this->datatables->from('galeri');
        $this->datatables->group_by('galeri.idkategori,galeri.idkategori');

        //add this line for join
        $this->datatables->join('kategori', 'kategori.idkategori = galeri.idkategori');
       

       $this->datatables->add_column('Total', '
              <a href=" '.site_url('galeri/totaldetail/$2').' " class="totaldetail_record
               label label-sm label-success" data-code="$1" 
              data-hapus="$1">  $3</a>  ',  'idgalery,idkategori,total');

$this->datatables->add_column('action', '
  <a href="javascript:void(0);" class="delete_record label label-sm label-danger" data-code="$1" 
  onclick="javasciprt: return confirm(\'Are You Sure ?\')"data-hapus="$1"><i class="fa fa-trash-o"></i> Hapus</a>  ',  'idgalery,total');

        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idgalery', $q);
	$this->db->or_like('idkategori', $q);
	$this->db->or_like('foto', $q);
	$this->db->or_like('create_date', $q);
	$this->db->or_like('modif_date', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idgalery', $q);
	$this->db->or_like('idkategori', $q);
	$this->db->or_like('foto', $q);
	$this->db->or_like('create_date', $q);
	$this->db->or_like('modif_date', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
      $cek =    $this->db->insert($this->table, $data);
        
        if ($cek) {
            # code...
        return true;
        }else{
            return false;
        }
    }


    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Galeri_model.php */
/* Location: ./application/models/Galeri_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-05-11 11:09:53 */
/* http://harviacode.com */