<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Gambar_model extends CI_Model
{

    public $table = 'gambar';
    public $id = 'id_gambar';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_gambar,gambai,gambar_admin');
        $this->datatables->from('gambar');
        //add this line for join
        //$this->datatables->join('table2', 'gambar.field = table2.field');
        $this->datatables->add_column('action', '


     
                                                   
                                             
                                                   <a href="javascript:void(0);" class="edit_record  label label-sm label-info" data-code="$1" ><i class="fa fa-pencil"></i> Edit</a>
                                               
                                                    <a href="javascript:void(0);" class="delete_record label label-sm label-danger" data-code="$1" data-nama_kategori="$2"><i class="fa fa-trash-o"></i> Hapus</a>
                                          


        ',  'idkategori,nama_kategori');


        
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_gambar', $q);
	$this->db->or_like('gambai', $q);
	$this->db->or_like('gambar_admin', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_gambar', $q);
	$this->db->or_like('gambai', $q);
	$this->db->or_like('gambar_admin', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Gambar_model.php */
/* Location: ./application/models/Gambar_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-05-05 09:55:29 */
/* http://harviacode.com */