<?php

if (!defined('BASEPATH'))
	exit('No direct script access allowed');

class Kategori_model extends CI_Model
{

	public $table = 'kategori';
	public $id = 'idkategori';
	public $order = 'DESC';

	function __construct()
	{
		parent::__construct();
	}

	// datatables
	function json()
	{
		$this->datatables->select('idkategori,
									nama_kategori,
									status,
									hargaBW,
									hargaColor,
									hargajilid ');
		$this->datatables->from('kategori');
		//add this line for join
		//$this->datatables->join('table2', 'kategori.field = table2.field');

		$this->datatables->add_column('action', '
 		<a href="javascript:void(0);" class="edit_record  label label-sm label-info" data-code="$1" ><i class="fa fa-pencil"></i> Edit</a>
         <a href="javascript:void(0);" class="delete_record label label-sm label-danger" data-code="$1" data-nama_kategori="$2"><i class="fa fa-trash-o"></i> Hapus</a>
           ',  'idkategori,nama_kategori');


		return $this->datatables->generate();
	}

	// get all
	function get_all()
	{
		$this->db->order_by($this->id, $this->order);
		return $this->db->get($this->table)->result();
	}


	// get all
	function get_allKategori()
	{
		$this->db->order_by('idkategori', $this->order);
		$this->db->where('status', '1');
		return $this->db->get('kategori')->result();
	}

	function alreadykategoriupdate($kategori, $statusaktif)
	{
		$this->db->where('nama_kategori', $kategori);
		$this->db->where('status', $statusaktif);
		return $this->db->get($this->table);
	}

	function alreadykategori($kategori)
	{
		$this->db->where('nama_kategori', $kategori);

		return $this->db->get($this->table);
	}

	// get data by id
	function get_by_id($id)
	{
		$this->db->where($this->id, $id);
		return $this->db->get($this->table)->row();
	}

	// get total rows
	function total_rows($q = NULL)
	{
		$this->db->like('idkategori', $q);
		$this->db->or_like('nama_kategori', $q);
		$this->db->or_like('status', $q);
		$this->db->or_like('create_date', $q);
		$this->db->or_like('modif_date', $q);
		$this->db->from($this->table);
		return $this->db->count_all_results();
	}

	// get data with limit and search
	function get_limit_data($limit, $start = 0, $q = NULL)
	{
		$this->db->order_by($this->id, $this->order);
		$this->db->like('idkategori', $q);
		$this->db->or_like('nama_kategori', $q);
		$this->db->or_like('status', $q);
		$this->db->or_like('create_date', $q);
		$this->db->or_like('modif_date', $q);
		$this->db->limit($limit, $start);
		return $this->db->get($this->table)->result();
	}

	// insert data
	function insert($data)
	{
		$this->db->insert($this->table, $data);
	}

	// update data
	function update($id, $data)
	{
		$this->db->where($this->id, $id);
		$this->db->update($this->table, $data);
	}

	// delete data
	function delete($id)
	{
		$this->db->where($this->id, $id);
		$this->db->delete($this->table);
	}
}

/* End of file Kategori_model.php */
/* Location: ./application/models/Kategori_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-05-11 11:09:54 */
/* http://harviacode.com */
