<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Webfrofil_model extends CI_Model
{

    public $table = 'webfrofil';
    public $id = 'id_webfrofil';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_webfrofil,namaweb,email,tlp,logo');
        $this->datatables->from('webfrofil');
        //add this line for join
        //$this->datatables->join('table2', 'webfrofil.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('webfrofil/read/$1'),'Read')." | ".anchor(site_url('webfrofil/update/$1'),'Update')." | ".anchor(site_url('webfrofil/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_webfrofil');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_webfrofil', $q);
	$this->db->or_like('namaweb', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('tlp', $q);
	$this->db->or_like('logo', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_webfrofil', $q);
	$this->db->or_like('namaweb', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('tlp', $q);
	$this->db->or_like('logo', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Webfrofil_model.php */
/* Location: ./application/models/Webfrofil_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-05-05 10:04:02 */
/* http://harviacode.com */