<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Webprofil_model extends CI_Model
{

    public $tableuser = 'users';
    public $tableprofil = 'webprofil';
    public $id = 'idwebprofil';
    public $iduser = 'iduser';

    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
       return $this->db->get($this->tableuser)->result();
    }

      function jsonprofil() {
       return $this->db->get($this->tableprofil)->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id_user($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idwebprofil', $q);
	$this->db->or_like('namaweb', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('tlp1', $q);
	$this->db->or_like('tlp2', $q);
	$this->db->or_like('tlp3', $q);
	$this->db->or_like('fb', $q);
	$this->db->or_like('ig', $q);
	$this->db->or_like('create_date', $q);
	$this->db->or_like('midif_date', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idwebprofil', $q);
	$this->db->or_like('namaweb', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('tlp1', $q);
	$this->db->or_like('tlp2', $q);
	$this->db->or_like('tlp3', $q);
	$this->db->or_like('fb', $q);
	$this->db->or_like('ig', $q);
	$this->db->or_like('create_date', $q);
	$this->db->or_like('midif_date', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update_user($id, $data)
    {
        $this->db->where($this->iduser, $id);
         $this->db->update($this->tableuser, $data);
    }

       function update_profil($id, $data)
    {
        $this->db->where('idwebprofil', $id);
          $this->db->update('webprofil', $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Webprofil_model.php */
/* Location: ./application/models/Webprofil_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-05-11 11:09:55 */
/* http://harviacode.com */